name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
    paths:
      - apps/swirl-docs/**
      - .github/workflows/azure-static-web-apps-kind-beach-0451f6803.yml
      - azure-static-web-apps-kind-beach-0451f6803.yml
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - apps/swirl-docs/**
      - azure-static-web-apps-kind-beach-0451f6803.yml

jobs:
  build_and_deploy_job:
    if:
      github.event_name == 'push' || (github.event_name == 'pull_request' &&
      github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "16.13"

      - name: Install Packages
        run: yarn

      - name: Build
        run: yarn build

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token:
            ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_KIND_BEACH_0451F6803 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          skip_app_build: true
          skip_api_build: true
          app_location: "apps/swirl-docs/build" # App source code path
          api_location: "" # Api source code path - optional
          output_location: ""
          # output_location: "apps/swirl-docs/build/standalone/build" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
        env: # Add environment variables here
          is_static_export: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token:
            ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_KIND_BEACH_0451F6803 }}
          action: "close"
